services:
  mysql_db_python_single:
    image: mysql:8.0 # Se selecciona la imagen de MYSQL de DockerHub
    container_name: mysql_db_python_single
    environment: # se establecen las variables de ambiente
      MYSQL_ROOT_PASSWORD: mipassword
      MYSQL_DATABASE: crud_python
      MYSQL_USER: usuario             
      MYSQL_PASSWORD: mipassword 
    command: --port=3310   
    ports: # Se expone el puerto 3310
      - "3310:3310"
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d  # Se inicializan los archivos .SQL
      - db_python_app_single:/var/lib/mysql # Se establece 

  python_app_single: # Pull de la imagen de DockerHub
    image: dockerdepruebas/dockerpython-python_app_single
    container_name: python_app_single
    ports: # exponemos el puerto 5601
      - "5601:5600"
    depends_on:  # establecemos que depende del contenedor de Mysql
      - mysql_db_python_single

volumes: # Se crea el volumen de myql
  db_python_app_single: